Added maths expression alt text example
springernature/frontend-playbook pull request #466
Opened 2024-01-16 16:20 UTC by cmuncharaz

Added en example explaining how to write alt text for images of mathematical expressions.

2024-01-16 16:41 UTC, ruthmoog requested changes
Really cool addition, thanks!

- suggestions for readability and fix examples so they match the image

2024-01-16 16:41 UTC, ruthmoog commented on accessibility/alt-text.md
> +* "Fraction where the numerator is a plus b and the denominator is c."
```suggestion
* "Fraction where the numerator is a plus b and the denominator is d."
```

2024-01-16 16:41 UTC, ruthmoog commented on accessibility/alt-text.md
> +![Screenshot of a faction where the numerator is a plus b and the denominator is c](images/alt-examples/maths.png)
```suggestion
![Fraction where the numerator is a plus b and the denominator is d](images/alt-examples/maths.png)
```

2024-01-16 16:41 UTC, ruthmoog commented on accessibility/alt-text.md
> +In the case of images of mathematical expressions, the alt text should describe the expression in spoken mathematics. Avoid using special characters matching mathematical symbols, such as operators,
```suggestion
In the case of images of mathematical expressions, the alt text should describe the expression in spoken mathematics. Avoid using symbols or characters with mathematical usages (such as operators, fractions, units etc) which may not be announced as expected by screen readers.
```

2024-01-29 11:51 UTC, RSeidelsohn approved these changes
This looks like a great addition!

2024-01-29 12:02 UTC, ruthmoog requested changes

2024-01-29 12:02 UTC, ruthmoog commented on accessibility/alt-text.md
> +* "(a + b) / c"
```suggestion
* "(a + b) / d"
```

2024-01-29 12:02 UTC, ruthmoog commented on accessibility/alt-text.md
> +* "The quantity of a plus b divided by c."
```suggestion
* "The quantity of a plus b divided by d."
```
Sorry didn't see these ones earlier! having all the same helps with clarity

2024-01-29 12:02 UTC, ruthmoog approved these changes

2024-01-29 12:10 UTC, merged