Replace SASS with Sass
springernature/frontend-playbook pull request #473
Opened 2024-03-07 15:50 UTC by josebolos

Apparently, the sass developers preferred way of writing SASS is Sass.

Also replace a URL that was being redirected with the canonical one, and add a couple of 'S' to a couple of 'HTTP'.

2024-03-07 15:56 UTC, benjclark approved these changes, later dismissed
Outstanding

2024-03-07 15:59 UTC, alexkilgour commented on css/house-style.md
> +Sass code should be linted with [sass-lint](https://github.com/sasstools/sass-lint) using the [Springer Nature
```suggestion
Sass code should be linted with [Stylelint](https://stylelint.io/) using the [Springer Nature
```
We are using stylelint now!

2024-03-07 15:59 UTC, alexkilgour commented on css/house-style.md
>  `sasslint-config`](https://github.com/springernature/sasslint-config-springernature). This configuration allows us to maintain consistency between different projects.
```suggestion
`stylelint-config`](https://github.com/springernature/stylelint-config-springernature). This configuration allows us to maintain consistency between different projects.
```

2024-05-01 09:23 UTC, ruthmoog requested changes
Love these corrections ✨

2024-05-01 09:23 UTC, ruthmoog commented on css/house-style.md
> +Our preferred CSS preprocessor is [Sass using the SCSS syntax](how-we-write-css.md).
I reckon we should keep the link to Sass docs and, make the link to the md explicit.

```suggestion
Our preferred CSS preprocessor is [Sass](https://sass-lang.com) using the SCSS syntax. Find out about [how we write CSS](how-we-write-css.md).
```

2024-05-02 13:21 UTC, ruthmoog approved these changes
I agree with Alex's stylelint-config suggestion for ln93 - have committed that suggestion

2024-05-02 13:32 UTC, merged

2024-05-02 13:32 UTC, jpw commented
thanks all!